export const data=[
    {
        id:1,
        name:"rahul",
        age:"24",
        country:"India",
        image:"https://unsplash.com/photos/iFgRcqHznqg"

    },
    {
        id:2,
        name:"joe",
        age:"34",
        country:"germany",
        image:"https://unsplash.com/photos/N8lRH2uxih4"
    },
    {
        id:3,
        name:"jae",
        age:"35",
        country:"germany",
        image:"https://unsplash.com/photos/vAVGdV1oklQ"
    },
    {
        id:4,
        name:"Maya",
        age:"72",
        country:"Alaska",
        image:"https://unsplash.com/photos/O3ymvT7Wf9U"
    },
    {
        id:5,
        name:"Arun",
        age:"27",
        country:"India",
        image:"https://unsplash.com/photos/HrpYHchKb5Y"
    },
    {
        id:6,
        name:"Varsha",
        age:"28",
        country:"India",
        image:"https://unsplash.com/collections/j8zHHoDlyQM/thesis"
    },
    {
        id:7,
        name:"Stella",
        age:"34",
        country:"England",
        image:"https://www.istockphoto.com/photo/portrait-of-natural-beauty-woman-at-beach-gm1369509530-439254148?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_top&utm_content=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Ffaces&utm_term=faces%3A%3A%3A"
    },
    {
        id:8,
        name:"Jenniffer",
        age:"34",
        country:"germany",
        image:"https://unsplash.com/photos/jzY0KRJopEI"
    },
]